# Referenced from GitLab's template Maven CI
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

variables:
    # Java
    MAVEN_DOCKER: maven:3-eclipse-temurin-11
    MAVEN_SETTINGS: ".build/gitlab-maven-settings.xml"
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true" # https://maven.apache.org/configure.html
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -DaltDeploymentRepository=gitlab-maven::${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven"

stages:
    - deploy

default:
    image: alpine:latest
    retry:
        max: 2
        when: runner_system_failure
    artifacts:
        expire_in: 1 week

maven-deploy:
    stage: deploy
    image: $MAVEN_DOCKER
    script:
        # https://stackoverflow.com/a/38148135
        - mvn $MAVEN_CLI_OPTS -s $MAVEN_SETTINGS -P library jar:jar deploy:deploy
